const tags = [
  { tagName: "Arduino User Group" },
  { tagName: "Art" },
  { tagName: "Audio" },
  { tagName: "Cars" },
  { tagName: "Clocks" },
  { tagName: "Communication" },
  { tagName: "Data Collection" },
  { tagName: "Debugging Tools" },
  { tagName: "Disability Reduction" },
  { tagName: "Embedded" },
  { tagName: "Energy Efficiency" }, 
  { tagName: "Entertainment System" },
  { tagName: "Environmental Sensing" },
  { tagName: "Food And Drinks" },
  { tagName: "Games" },
  { tagName: "Garden" }, 
  { tagName: "Greener Planet" },
  { tagName: "Health" },
  { tagName: "Helicopters" },
  { tagName: "Home Automation" },
  { tagName: "Human Welfare" }, 
  { tagName: "Internet Of Things" },
  { tagName: "Kids" },
  { tagName: "Lights" },
  { tagName: "Monitoring" },
  { tagName: "Music" },
  { tagName: "Passenger Vehicles" },
  { tagName: "Pets" },
  { tagName: "Planes" },
  { tagName: "Remote Control" },
  { tagName: "Security" },
  { tagName: "Smart appliances" },
  { tagName: "Smartwatches" },
  { tagName: "Tools" },
  { tagName: "Toys" },
  { tagName: "Tracking" },
  { tagName: "Transportation" },
  { tagName: "Wardriving" },
  { tagName: "Wearables" },
  { tagName: "Weather" },
  { tagName: "Animals" },
]

export default tags
